-- MySQL Script generated by MySQL Workbench
-- 02/05/18 12:11:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema netliveio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema netliveio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `netliveio` DEFAULT CHARACTER SET utf8 ;
USE `netliveio` ;

-- -----------------------------------------------------
-- Table `netliveio`.`onlinestate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `netliveio`.`onlinestate` (
  `onlinestate_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `onlinestate` VARCHAR(255) NULL,
  `order` INT NULL DEFAULT 100,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`onlinestate_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netliveio`.`userstate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `netliveio`.`userstate` (
  `userstate_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `userstate` VARCHAR(255) NULL,
  `onlinestate_id` INT UNSIGNED NOT NULL,
  `order` INT NULL DEFAULT 100,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`userstate_id`),
  INDEX `fk_userstate_onlinestate1_idx` (`onlinestate_id` ASC),
  CONSTRAINT `fk_userstate_onlinestate1`
    FOREIGN KEY (`onlinestate_id`)
    REFERENCES `netliveio`.`onlinestate` (`onlinestate_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netliveio`.`userpermission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `netliveio`.`userpermission` (
  `userpermission_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `userpermission` VARCHAR(255) NULL,
  `onlinestate_id` INT UNSIGNED NOT NULL,
  `order` INT NULL DEFAULT 100,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`userpermission_id`),
  INDEX `fk_userpermission_onlinestate1_idx` (`onlinestate_id` ASC),
  CONSTRAINT `fk_userpermission_onlinestate1`
    FOREIGN KEY (`onlinestate_id`)
    REFERENCES `netliveio`.`onlinestate` (`onlinestate_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netliveio`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `netliveio`.`user` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `salutation_id` INT NULL,
  `firstname` VARCHAR(255) NULL,
  `lastname` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `userstate_id` INT UNSIGNED NOT NULL DEFAULT 1,
  `userpermission_id` INT UNSIGNED NOT NULL DEFAULT 1,
  `created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `last_login` DATETIME NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`user_id`),
  INDEX `fk_user_userstatus_idx` (`userstate_id` ASC),
  INDEX `fk_user_userpermission1_idx` (`userpermission_id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  CONSTRAINT `fk_user_userstatus`
    FOREIGN KEY (`userstate_id`)
    REFERENCES `netliveio`.`userstate` (`userstate_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_userpermission1`
    FOREIGN KEY (`userpermission_id`)
    REFERENCES `netliveio`.`userpermission` (`userpermission_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netliveio`.`user_forgotpassword`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `netliveio`.`user_forgotpassword` (
  `forgotpassword_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `hash` VARCHAR(255) NULL,
  `created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `isActivated` TINYINT(1) NULL DEFAULT 0,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`forgotpassword_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
