-- MySQL Script generated by MySQL Workbench
-- 01/31/18 16:12:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema netliveio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema netliveio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `netliveio` DEFAULT CHARACTER SET utf8 ;
USE `netliveio` ;

-- -----------------------------------------------------
-- Table `netliveio`.`onlinestate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `netliveio`.`onlinestate` (
  `onlinestate_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `onlinestate` VARCHAR(255) NULL,
  `deleted` TINYINT(1) NULL,
  PRIMARY KEY (`onlinestate_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netliveio`.`userstate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `netliveio`.`userstate` (
  `userstate_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order` INT NULL,
  `onlinestate_id` INT UNSIGNED NOT NULL,
  `deleted` TINYINT(1) NULL,
  `userstate` VARCHAR(255) NULL,
  PRIMARY KEY (`userstate_id`),
  INDEX `fk_userstate_onlinestate1_idx` (`onlinestate_id` ASC),
  CONSTRAINT `fk_userstate_onlinestate1`
    FOREIGN KEY (`onlinestate_id`)
    REFERENCES `netliveio`.`onlinestate` (`onlinestate_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netliveio`.`userpermission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `netliveio`.`userpermission` (
  `userpermission_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order` INT NULL,
  `deleted` TINYINT(1) NULL,
  `userpermission` VARCHAR(255) NULL,
  `onlinestate_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`userpermission_id`),
  INDEX `fk_userpermission_onlinestate1_idx` (`onlinestate_id` ASC),
  CONSTRAINT `fk_userpermission_onlinestate1`
    FOREIGN KEY (`onlinestate_id`)
    REFERENCES `netliveio`.`onlinestate` (`onlinestate_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netliveio`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `netliveio`.`user` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `last_login` DATETIME NULL,
  `firstname` VARCHAR(255) NULL,
  `lastname` VARCHAR(255) NULL,
  `salutation_id` INT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `created` DATETIME NULL,
  `deleted` TINYINT(1) NULL,
  `userstate_id` INT UNSIGNED NOT NULL,
  `userpermission_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_user_userstatus_idx` (`userstate_id` ASC),
  INDEX `fk_user_userpermission1_idx` (`userpermission_id` ASC),
  CONSTRAINT `fk_user_userstatus`
    FOREIGN KEY (`userstate_id`)
    REFERENCES `netliveio`.`userstate` (`userstate_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_userpermission1`
    FOREIGN KEY (`userpermission_id`)
    REFERENCES `netliveio`.`userpermission` (`userpermission_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
